### ISSUE TITLE
Install Script for Production Environment

### ISSUE THREAD

**Issue by KyleAHinton** [KyleAHinton/ShutterBug#6]
An install script, in either Bash or Python, that installs the necessary components of the software. So that it can be installed and run effortlessly on a production system.

**Comment by rebeljedi999** [comment]
This will be shelved and worked on if there is time

**Comment by rebeljedi999** [comment]
Did not have time

**Comment by rebeljedi999** [comment]
Created install script for developer environment on ubuntu
